# Generated by Django 4.2.16 on 2026-03-20 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_counter_productcounter_offering_offer_and_more'),
        ('orders', '0006_order_auto_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.counter'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_code',
            field=models.CharField(blank=True, db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
