# Generated by Django 6.0.3 on 2026-03-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_building_state_city_building_city'),
        ('menu', '0010_site_price_stock_ledger_web_qty'),
        ('orders', '0008_order_offer_discount_item_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_tickets', to='core.company')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='menu.counter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_tickets', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
