# Generated by Django 4.2.16 on 2026-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_counter_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterticket',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counterticket',
            name='scan_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
