# Generated by Django 4.2.16 on 2026-04-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_wallet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
