# Generated by Django 4.2.16 on 2026-04-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_customer_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(0, 'Home / Office Delivery'), (1, 'Pickup from Counter'), (2, 'Office Cafeteria'), (3, 'Wallet Recharge')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('online', 'Online Payment'), ('monthly', 'Monthly Billing'), ('company', 'Bill to Company'), ('wallet', 'Wallet')], default='online', max_length=20),
        ),
    ]
