# Generated by Django 4.2.16 on 2026-03-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mediaasset_advertise_scheduling_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertise',
            options={'ordering': ['position_order', '-created_at']},
        ),
    ]
