# Generated by Django 4.2.16 on 2026-03-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_advertise_options'),
        ('menu', '0004_holidayschedule_advertise_companies_holiday'),
    ]

    operations = [
    ]
