# Generated by Django 4.2.16 on 2026-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_cod_payment_and_more'),
        ('menu', '0005_merge_20260318_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Select which sites to show this banner on. Leave empty to show only on your own site.', related_name='targeted_adverts', to='core.company'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='holiday_schedules',
            field=models.ManyToManyField(blank=True, help_text='Also run this ad automatically on selected national holidays every year', related_name='adverts', to='menu.holidayschedule'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Additional sites that can use this image', related_name='shared_assets', to='core.company'),
        ),
    ]
