# Generated by Django 4.2.16 on 2026-03-19 17:51

import apps.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_advertise_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload 1240 × 660 px (or larger in the same ratio) for the customer portal banner', null=True, upload_to=apps.menu.models.advert_image_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='image',
            field=models.ImageField(help_text='Upload 1240 × 660 px (or larger in the same ratio) so it fits the customer portal banner', upload_to=apps.menu.models.media_asset_path),
        ),
    ]
