# Generated by Django 6.0.3 on 2026-03-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_building_state_city_building_city'),
        ('menu', '0009_counter_productcounter_offering_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='web_qty',
            field=models.IntegerField(default=-1, help_text='-1 = unlimited web stock; >=0 = capped'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'Web Order'), ('pos', 'POS Order'), ('manual', 'Manual Adjustment')], default='web', max_length=10)),
                ('ref_id', models.IntegerField(default=0, help_text='Order PK or POS order PK')),
                ('qty', models.IntegerField(help_text='Negative = deduct, positive = restock')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='menu.product')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompanyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_prices', to='menu.product')),
            ],
            options={
                'verbose_name': 'Site-wise Price',
                'unique_together': {('product', 'company')},
            },
        ),
    ]
