# Generated by Django 4.2.16 on 2026-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_site_price_stock_ledger_web_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='auto_print_on_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counter',
            name='auto_print_on_scan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='printer_label',
            field=models.CharField(blank=True, help_text='Optional browser/printer label for this counter POS.', max_length=120),
        ),
    ]
