# Generated by Django 4.2.16 on 2026-03-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_company_kiosk_logo_and_more'),
        ('menu', '0017_product_schedule_bypass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_kiosk_active',
            field=models.BooleanField(default=True, help_text='Controls visibility in the self-service kiosk. Independent of the web (customer portal) active status.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='schedule_bypass',
            field=models.BooleanField(default=False, help_text="SUPERADMIN ONLY: When enabled, this product always appears in the menu regardless of its parent Offering or Category schedule. The product's own time/date settings still apply."),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global/shared image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='core.company'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='name',
            field=models.CharField(help_text='Descriptive label for this image', max_length=255),
        ),
    ]
