# Generated by Django 4.2.16 on 2026-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_product_featured_in_kiosk_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_in_kiosk_extra',
            field=models.BooleanField(default=False, help_text='Show this product in the "Featured" section on the kiosk (max 10 shown).'),
        ),
    ]
