# Generated by Django 4.2.16 on 2026-03-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_offer_products_m2m_type_cart_offer_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Single product. Leave blank for multi-product or cart-level offers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='menu.product'),
        ),
    ]
