# Generated by Django 4.2.16 on 2026-03-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_alter_offer_product'),
        ('menu', '0024_offer_flat_type_min_order_max_discount'),
    ]

    operations = [
    ]
