# Generated by Django 4.2.16 on 2026-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_merge_20260330_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PERCENT/CART: percentage (0-100). FLAT: rupee amount off.', max_digits=10),
        ),
    ]
