# Generated by Django 4.2.16 on 2026-04-01 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_offer_usage_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Category-level preparation time in minutes used for auto-ready. 0 = no category-level override (falls back to product level). When set, this overrides per-product preparation time for orders in this category, and orders become auto-ready after confirmation.'),
        ),
        migrations.AlterField(
            model_name='offerusage',
            name='used_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
