# Generated by Django 4.2.16 on 2026-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_is_approved_and_more'),
        ('menu', '0030_alter_category_preparation_time_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offerusage',
            name='uniq_offer_customer_used_on',
        ),
        migrations.AlterField(
            model_name='category',
            name='preparation_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes after confirmation before items in this category should be marked ready. 0 = manual flow.'),
        ),
        migrations.AlterUniqueTogether(
            name='offerusage',
            unique_together={('offer', 'customer', 'used_on')},
        ),
    ]
