# Generated by Django 4.2.16 on 2026-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0035_schedule_offering_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room_service_extra_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage added to the visitor price for room service orders.', max_digits=5),
        ),
    ]
