# Generated by Django 4.2.16 on 2026-04-28 12:57

from django.db import migrations, models
import django.db.models.deletion


def seed_category_company_statuses(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')
    CategoryCompanyStatus = apps.get_model('menu', 'CategoryCompanyStatus')

    rows = []
    for category in Category.objects.filter(is_deleted=False).prefetch_related('companies'):
        for company in category.companies.all():
            rows.append(CategoryCompanyStatus(
                category_id=category.pk,
                company_id=company.pk,
                is_active=category.is_active,
            ))
    CategoryCompanyStatus.objects.bulk_create(rows, ignore_conflicts=True)


def unseed_category_company_statuses(apps, schema_editor):
    apps.get_model('menu', 'CategoryCompanyStatus').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification_image'),
        ('menu', '0036_product_room_service_extra_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_statuses', to='menu.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_statuses', to='core.company')),
            ],
            options={
                'ordering': ['category__position_order', 'category__name', 'company__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorycompanystatus',
            constraint=models.UniqueConstraint(fields=('category', 'company'), name='uniq_category_company_status'),
        ),
        migrations.RunPython(seed_category_company_statuses, unseed_category_company_statuses),
    ]
