# Generated by Django 4.2.16 on 2026-04-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification_image'),
        ('menu', '0037_categorycompanystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycompanystatus',
            name='open_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='categorycompanystatus',
            name='use_custom_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_schedules', to='core.company'),
        ),
    ]
