# Generated by Django 4.2.16 on 2026-03-17 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.TextField()),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('verification_key', models.CharField(blank=True, max_length=250)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(default=0)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('token_expires', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('cod_payment', models.BooleanField(default=False)),
                ('monthly_payment', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.building')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, max_length=255)),
                ('delivery_type', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Company Admin'), ('cafeman', 'Chef / Cafe Manager'), ('pos', 'Cashier / POS'), ('reports', 'Reports Viewer')], default='admin', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Staff User',
                'ordering': ['name'],
            },
        ),
    ]
