# Generated by Django 4.2.16 on 2026-03-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dashboardmenuaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardMenuAccess',
        ),
    ]
