# Generated by Django 4.2.16 on 2026-03-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffaccess_landing_page'),
        ('accounts', '0004_delete_dashboardmenuaccess'),
    ]

    operations = [
    ]
