# Generated by Django 4.2.16 on 2026-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_meal_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subsidy_amount_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-customer subsidy override. Leave blank to use company subsidy amount.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subsidy_eligible',
            field=models.BooleanField(default=False, help_text='Legacy flag. Use meal_benefit for new logic.'),
        ),
    ]
