# Generated by Django 4.2.16 on 2026-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_wallet_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Set False to require admin approval before customer can order. New registrations can be auto-set to False via company settings.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='royalty_points',
            field=models.IntegerField(default=0, help_text='Accumulated royalty points. 1 point = 1 rupee when redeemed via wallet.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Topup balance in ₹ (separate from royalty points)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_by',
            field=models.CharField(blank=True, help_text='Staff email or "system"', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='order_ref',
            field=models.CharField(blank=True, help_text='Order number if related to an order', max_length=50),
        ),
    ]
