# Generated by Django 4.2.16 on 2026-04-14 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customer_meal_benefit_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('object_label', models.CharField(max_length=255)),
                ('field_diffs', models.JSONField(help_text='{"field_key": {"label": "...", "before": ..., "after": ...}}')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Change',
                'verbose_name_plural': 'Pending Changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('view', 'View Only'), ('part_edit', 'Part Edit'), ('full_edit', 'Full Edit (Pending Approval)')], max_length=20)),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text='Specific action keys (only used when level=part_edit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Module Permission',
                'verbose_name_plural': 'Staff Module Permissions',
                'ordering': ['staff_user__name', 'module_key'],
                'unique_together': {('staff_user', 'module_key')},
            },
        ),
    ]
