# Generated by Django 4.2.16 on 2026-03-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_gst', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('order_from_time', models.TimeField(blank=True, null=True)),
                ('order_to_time', models.TimeField(blank=True, null=True)),
                ('delivery_time', models.IntegerField(default=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('bill_company', models.IntegerField(choices=[(1, 'Employee Pays'), (2, 'Bill to Company')], default=2)),
                ('company_meal_amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Subsidy amount company covers per meal', max_digits=10, null=True)),
                ('cod_payment', models.BooleanField(default=False)),
                ('store_status', models.BooleanField(default=True)),
                ('store_order_enabled', models.BooleanField(default=False)),
                ('video_link', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'State',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='core.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
