# Generated by Django 4.2.16 on 2026-03-20 07:24

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_order_open_days_company_free_meal_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='order_open_days',
            field=models.JSONField(blank=True, default=apps.core.models.default_order_open_days),
        ),
    ]
