# Generated by Django 4.2.16 on 2026-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_kioskconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kiosk_logo',
            field=models.ImageField(blank=True, help_text='Override logo shown on the kiosk screen only', null=True, upload_to='company/kiosk_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kiosk_theme_color',
            field=models.CharField(blank=True, default='#1e3a5f', help_text='Primary hex colour for kiosk header', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='monthly_payment',
            field=models.BooleanField(default=False, help_text='Allow monthly billing in web orders'),
        ),
        migrations.AlterField(
            model_name='company',
            name='online_payment',
            field=models.BooleanField(default=True, help_text='Allow online/UPI payment in web & kiosk'),
        ),
        migrations.AlterField(
            model_name='company',
            name='require_customer_approval',
            field=models.BooleanField(default=False, help_text='New customer registrations need admin approval before ordering.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='royalty_max_redeem_pct',
            field=models.IntegerField(default=50, help_text='Max % of order value payable by royalty points'),
        ),
        migrations.AlterField(
            model_name='company',
            name='royalty_points_per_rupee',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Points earned per ₹1 spent on a normal order (standard earn rate)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='royalty_rank1_points',
            field=models.IntegerField(default=500, help_text='Bonus pts for #1 customer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='royalty_rank2_points',
            field=models.IntegerField(default=250, help_text='Bonus pts for #2 customer'),
        ),
        migrations.AlterField(
            model_name='company',
            name='royalty_rank3_points',
            field=models.IntegerField(default=100, help_text='Bonus pts for #3 customer'),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='card_style',
            field=models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('large', 'Large')], default='standard', help_text='Product card display style', max_length=20),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='name',
            field=models.CharField(help_text='e.g. "Main Entrance Kiosk"', max_length=120),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-set. Used in kiosk URL: /kiosk/<company_id>/?kiosk=<slug>', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='kioskconfig',
            name='theme_color',
            field=models.CharField(blank=True, help_text='Hex colour override e.g. #c62828', max_length=20),
        ),
        migrations.AlterField(
            model_name='royaltyaward',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='royaltyaward',
            name='period_key',
            field=models.CharField(help_text='e.g. 2025-01 (monthly), 2025-W03 (weekly), 2025-01-15 (daily)', max_length=20),
        ),
        migrations.AlterField(
            model_name='royaltyaward',
            name='rank',
            field=models.IntegerField(help_text='1=first, 2=second, 3=third'),
        ),
    ]
