# Generated by Django 4.2.16 on 2026-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_company_order_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kiosk_order_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for kiosk orders (e.g. "KIO"). Leave blank for default "KIO".', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='web_order_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for web orders (e.g. "WEB"). Leave blank for default "WEB".', max_length=10),
        ),
    ]
