# Generated by Django 4.2.16 on 2026-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_company_kiosk_order_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='kiosk_order_prefix',
        ),
        migrations.RemoveField(
            model_name='company',
            name='web_order_prefix',
        ),
    ]
