# Generated by Django 4.2.16 on 2026-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_webviewconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webviewconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
