# Generated by Django 4.2.16 on 2026-04-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_webviewconfig_id'),
        ('core', '0018_displayboardconfig'),
    ]

    operations = [
    ]
