# Generated by Django 4.2.16 on 2026-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_webviewconfig_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('system', 'System'), ('promo', 'Promotion'), ('broadcast', 'Broadcast'), ('wallet', 'Wallet')], default='order', max_length=20),
        ),
    ]
