# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
